/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProgressDialog.java
 *
 * Created on 20-May-2011, 18:21:13
 */

package IAClasses;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author barry05
 */
public class ProgressDialog extends javax.swing.JDialog {
    private String label;

    /** Creates new form ProgressDialog */
    public ProgressDialog(java.awt.Frame parent, String label, boolean modal, boolean alwaysOnTop, String title) {
        super(parent, title, modal);
        this.label = label;
        setAlwaysOnTop(alwaysOnTop);
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getWidth() / 2, dim.height / 2 - this.getHeight() / 2);
    }

    public void updateProgress(double current, double max){
        bar.setMinimum(0);
        bar.setMaximum((int)Math.round(max));
        bar.setValue((int)Math.round(current));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabel1.setText(label);
        getContentPane().add(jLabel1);
        getContentPane().add(bar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
